"""initial migration

Revision ID: a8bf6c8e0a8d
Revises: 
Create Date: 2026-05-15 10:09:20.200636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a8bf6c8e0a8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'role',
               existing_type=mysql.TINYINT(),
               comment='Role: 0=SUPER_ADMIN, 1=HR_ADMIN, 2=EMPLOYEE',
               existing_comment='Role: 1=HR_ADMIN, 2=EMPLOYEE',
               existing_nullable=False)
    op.alter_column('sys_user', 'preferences',
               existing_type=mysql.JSON(),
               comment='User preferences (theme, etc)',
               existing_comment='用户偏好设置',
               existing_nullable=True)
    op.alter_column('tra_watch_progress', 'watched_seconds',
               existing_type=mysql.INTEGER(),
               comment='Watched seconds (current position)',
               existing_comment='Watched seconds',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tra_watch_progress', 'watched_seconds',
               existing_type=mysql.INTEGER(),
               comment='Watched seconds',
               existing_comment='Watched seconds (current position)',
               existing_nullable=False)
    op.alter_column('sys_user', 'preferences',
               existing_type=mysql.JSON(),
               comment='用户偏好设置',
               existing_comment='User preferences (theme, etc)',
               existing_nullable=True)
    op.alter_column('sys_user', 'role',
               existing_type=mysql.TINYINT(),
               comment='Role: 1=HR_ADMIN, 2=EMPLOYEE',
               existing_comment='Role: 0=SUPER_ADMIN, 1=HR_ADMIN, 2=EMPLOYEE',
               existing_nullable=False)
    # ### end Alembic commands ###
